return {
    ["workshop-1378549454"]={
      configuration_options={
        ["MemSpikeFix:"]=false,
        MemSpikeFixmaster_override=true,
        ["MemSpikeFixworkshop-1157975551"]="default",
        ["MemSpikeFixworkshop-1467200656"]="default",
        ["MemSpikeFixworkshop-1467214795"]="default",
        ["MemSpikeFixworkshop-345692228"]="default",
        ["MemSpikeFixworkshop-347079953"]="default",
        ["MemSpikeFixworkshop-347360448"]="default",
        ["MemSpikeFixworkshop-351325790"]="default",
        ["MemSpikeFixworkshop-358749986"]="default",
        ["MemSpikeFixworkshop-360722606"]="default",
        ["MemSpikeFixworkshop-367546858"]="default",
        ["MemSpikeFixworkshop-375850593"]="default",
        ["MemSpikeFixworkshop-375859599"]="default",
        ["MemSpikeFixworkshop-378160973"]="default",
        ["MemSpikeFixworkshop-439115156"]="default",
        ["MemSpikeFixworkshop-444235588"]="default",
        ["MemSpikeFixworkshop-458365884"]="default",
        ["MemSpikeFixworkshop-458587300"]="default",
        ["MemSpikeFixworkshop-460972875"]="default",
        ["MemSpikeFixworkshop-466732225"]="default",
        ["MemSpikeFixworkshop-553665029"]="default",
        ["MemSpikeFixworkshop-565979581"]="default",
        ["MemSpikeFixworkshop-572538624"]="default",
        ["MemSpikeFixworkshop-821278891"]="default",
        craftinghighlight=false
      },
      enabled=true
    },
    ["workshop-347079953"]={
      configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
      enabled=true
    },
    ["workshop-358749986"]={
      configuration_options={ IndicatorSize=3, MaxIndicator=7000, PlayerIndicators=1 },
      enabled=true
    },
    ["workshop-360722606"]={
      configuration_options={
        DFV_ClientPrediction="default",
        DFV_FueledSettings="default",
        DFV_PercentReplace="default",
        DFV_ShowACondition="default",
        DFV_ShowADefence="default",
        DFV_ShowAType="default",
        DFV_ShowDamage="default",
        DFV_ShowInsulation="default",
        DFV_ShowTemperature="default",
        DFV_ShowUses="default"
      },
      enabled=true
    },
    ["workshop-375850593"]={ configuration_options={  }, enabled=true },
    ["workshop-375859599"]={
      configuration_options={
        divider=5,
        random_health_value=0,
        random_range=0,
        send_unknwon_prefabs=false,
        show_type=0,
        unknwon_prefabs=1,
        use_blacklist=true
      },
      enabled=true
    },
    ["workshop-378160973"]={
      configuration_options={
        ENABLEPINGS=true,
        FIREOPTIONS=2,
        OVERRIDEMODE=false,
        SHAREMINIMAPPROGRESS=true,
        SHOWFIREICONS=true,
        SHOWPLAYERICONS=true,
        SHOWPLAYERSOPTIONS=2
      },
      enabled=true
    },
    ["workshop-444235588"]={
      configuration_options={
        deluxeEndoFirepitBurnRate=0.75,
        deluxeFirepitBurnRate=0.75,
        dropLoot="yes",
        endoDropLoot="yes",
        heatStarBurnRate=0.75,
        heatStarDropLoot="yes",
        iceStarBurnRate=0.75,
        iceStarDropLoot="yes",
        recipeCost="standard",
        starsSpawnHounds="no"
      },
      enabled=true
    },
    ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
    ["workshop-460972875"]={ configuration_options={ ["速度"]="默认" }, enabled=true },
    ["workshop-466732225"]={ configuration_options={  }, enabled=true },
    ["workshop-553665029"]={ configuration_options={  }, enabled=true },
    ["workshop-565979581"]={ configuration_options={ divider=5, show_type=0 }, enabled=true }
  }  